production:
  adapter: postgresql
  database: openfreemarket
  encoding: utf8
  pool: 5
  username: postgres
  password: password
production:
  
development:
  adapter: postgresql
  database: openfreemarket
  encoding: utf8
  pool: 5
  username: postgres
  password: password