development:
  adapter: postgresql
  encoding: unicode
  database: openfreemarket
  pool: 5
  username: postgres
  password: password
production:
  adapter: postgresql
  encoding: unicode
  database: openfreemarket
  pool: 5
  username: postgres
  password: password